version: "3.6"
 
services:
    db:
        image: mariadb
        restart: always
        #command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - ./db:/var/lib/mysql
        ports: 
            - "33306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass

    wordpress:
        image: wtest
        restart: always
        depends_on:  
            - "db"
        volumes: 
            - ./wordpress:/var/www/html
        ports: 
            - "8000:80"
        environment: 
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_PASSWORD: pass
            LOCAL_USER_ID: 1001
           

volumes: 
    wordpress:
    db: {}